name: CI

on:
  pull_request:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: 14

    - name: Install Dependencies
      run: yarn
    
    - name: Lint
      run: yarn lint

    - name: Build
      run: yarn build:prod